name: Build Commit

on:
  push:
    branches:
      - main
  pull_request:
    types:
      - synchronize
      - opened
      - reopened

defaults:
  run:
    shell: bash -eu {0}

env:
  GO_VERSION: "1.18"

jobs:

  test:
    name: Test
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-go@v2
        with:
          go-version: ${{ env.GO_VERSION }}
      - uses: actions/cache@v2
        with:
          path: |
            ~/.cache/go-build
            ~/go/pkg/mod
          key: golang-${{ runner.os }}-${{ hashFiles('**/go.sum') }}-${{ github.sha }}
          restore-keys: |
            golang-${{ runner.os }}-${{ hashFiles('**/go.sum') }}-
            golang-${{ runner.os }}-
      - run: go mod download
      - run: go vet ./pkg
      - run: |
          go test -v -vet=off -race -shuffle ${SHUFFLE_SEED} -coverprofile=coverage.txt -covermode=atomic ./pkg
        env:
          SHUFFLE_SEED: ${{ github.run_number }}
      - uses: codecov/codecov-action@v3
        if: always()
